config/routes.rb
Rails.application.routes.draw do
  get "admin" => "admin#index"

  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
  end

  controller :store do
    get "search" => :index
    post "search" => :index
  end

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  root "store#index", as: "store_index"
  resources :products do
    get :who_bought, on: :member
  end

  resources :support_requests, only: [:index, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Depot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="main">
      <h1><%=@page_title %></h1>
    </header>
    <section class="content">
      <nav class="side_nav">
        <ul>
          <li><a href="/">Home</a></li>
          <li><a href="/carts/<%= session[:cart_id] %>">My Cart</a></li>
          <% if !session[:user_id] %>
            <li><a href="/login">Login as Admin</a></li>
          <%end %>
          <%# <li><a href="/news">News</a></li>
          <li><a href="/contact">Contact</a></li> %>
        </ul>
        <% if session[:user_id] %>
          <nav class="logged_in_nav">
            <ul>
              <li><%= link_to 'Orders',orders_path %></li>
              <li><%= link_to 'Products', products_path %></li>
              <li><%= link_to 'Users', users_path %></li>
              <li><%= button_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </nav>
        <% end %>
        <% if @cart %>
          <div id="cart" class="carts">
            <%= render_if @cart && @cart.line_items.any?, @cart %>
          </div>
        <% end %>
      </nav>
      <main class='<%= controller.controller_name %>'>
        <%= yield %>
      </main>
    </section>
  </body>
</html>